### ISSUE TITLE
harvesting failing when a file cannot be downloaded

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anhalytics-core#53]
While running the harvesting process it was failing with the error 

```
[INFO ] fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester:              Downloading: https://tel.archives-ouvertes.fr/tel-00440417/file/SketchImage%2FPhysics-Based%2FContact%2FVideo%2FVriphysVFThesisPres.avi
[ERROR] fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester: The service is not reachable.
```

After managing to reproduce it and expose the underlying exception it turned out to be just a download problem: 

```
Exception in thread "main" fr.inria.anhalytics.commons.exceptions.ServiceException: The service is not reachable.
	at fr.inria.anhalytics.commons.utilities.Utilities.request(Utilities.java:453)
	at fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester.requestFile(OAIPMHHarvester.java:119)
	at fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester.downloadAnnexes(OAIPMHHarvester.java:104)
	at fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester.processTeis(OAIPMHHarvester.java:82)
	at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:50)
	at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
	at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
	at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
Caused by: java.io.FileNotFoundException: https://hal.inria.fr/inria-00180949/file/biocompress%2FBiocompress.c
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at fr.inria.anhalytics.commons.utilities.Utilities.request(Utilities.java:439)
	... 7 more
```

The agreed approach is to continue and log the error (log file or mongodb collection).

**Comment by lfoppiano** [comment]
The new behaviour is ignoring when a file cannot be downloaded but it's failing when inria.fr is unreacheable with a long explanation. 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: fr.inria.anhalytics.commons.exceptions.ServiceException: The service is not reachable. Aborting.
        at fr.inria.anhalytics.commons.utilities.Utilities.request(Utilities.java:446)
        at fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester.requestFile(OAIPMHHarvester.java:115)
        at fr.inria.anhalytics.harvest.oaipmh.OAIPMHHarvester.processTeis(OAIPMHHarvester.java:73)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:50)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        ... 6 more
Caused by: java.net.UnknownHostException: hal.inria.fr
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:635)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at fr.inria.anhalytics.commons.utilities.Utilities.request(Utilities.java:435)
        ... 12 more
```

Perhaps we should try to continue?

**Comment by lfoppiano** [comment]
This seems to be solved
