### ISSUE TITLE
java.lang.Throwable should not be throwed but wrapped on an Exception

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anhalytics-core#57]
Found this in the log while running `-exe generateTei` in the harvesting process: 

```
Empty data is provided to Wapiti tagger: java.lang.Throwable
	at org.grobid.core.jni.WapitiWrapper.label(WapitiWrapper.java:18)
	at org.grobid.core.jni.WapitiModel.label(WapitiModel.java:48)
	at org.grobid.core.engines.tagging.WapitiTagger.label(WapitiTagger.java:28)
	at org.grobid.core.engines.AbstractParser.label(AbstractParser.java:39)
	at org.grobid.core.engines.AffiliationAddressParser.processing(AffiliationAddressParser.java:71)
	at org.grobid.core.engines.Engine.processAffiliation(Engine.java:132)
	at fr.inria.anhalytics.harvest.grobid.MyGrobid.runGrobid(MyGrobid.java:31)
	at fr.inria.anhalytics.harvest.converters.HalTEIConverter.parseOrgsAddress(HalTEIConverter.java:153)
	at fr.inria.anhalytics.harvest.converters.HalTEIConverter.convertMetadataToTEIHeader(HalTEIConverter.java:60)
	at fr.inria.anhalytics.harvest.teibuild.TeiBuilder.createTEICorpus(TeiBuilder.java:56)
	at fr.inria.anhalytics.harvest.teibuild.TeiBuilderProcess.createTEICorpus(TeiBuilderProcess.java:87)
	at fr.inria.anhalytics.harvest.teibuild.TeiBuilderProcess.buildTEICorpus(TeiBuilderProcess.java:60)
	at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:90)
	at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
```

**Comment by lfoppiano** [comment]
This is perhaps not a problem anymore (I could not find the class MyGrobid, probably it was changed in commit 303833b
