### ISSUE TITLE
Java Heap Space when processing the knowledge base

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anhalytics-core#70]
Last time I've run the `initKb` 

```
java -Xmx2048m -jar target/anhalytics-kb-0.1-SNAPSHOT.one-jar.jar -exe initKnowledgeBase
```

I've encurred in the following problem: 

```
[INFO ] fr.inria.anhalytics.commons.dao.anhalytics.DAOFactory: Storing entry
[INFO ] fr.inria.anhalytics.kb.datamine.KnowledgeBaseFeeder: Extracting :hal-00579703
[INFO ] fr.inria.anhalytics.kb.datamine.KnowledgeBaseFeeder: #################################################################
[INFO ] fr.inria.anhalytics.commons.dao.anhalytics.DAOFactory: Stored
[INFO ] fr.inria.anhalytics.commons.dao.anhalytics.DAOFactory: Storing entry
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.sun.org.apache.xpath.internal.VariableStack.reset(VariableStack.java:141)
        at com.sun.org.apache.xpath.internal.VariableStack.<init>(VariableStack.java:51)
        at com.sun.org.apache.xpath.internal.XPathContext.<init>(XPathContext.java:463)
        at com.sun.org.apache.xpath.internal.XPathContext.<init>(XPathContext.java:312)
        at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:121)
        at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.eval(XPathExpressionImpl.java:109)
        at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:191)
        at fr.inria.anhalytics.kb.datamine.KnowledgeBaseFeeder.initKnowledgeBase(KnowledgeBaseFeeder.java:104)
        at fr.inria.anhalytics.kb.main.Main.processCommand(Main.java:69)
        at fr.inria.anhalytics.kb.main.Main.main(Main.java:50)
        ... 6 more
```

**Comment by lfoppiano** [comment]
Same problem occurred after I've launched it again :-( Seems there is a leak

**Comment by lfoppiano** [comment]
Here the analisys with JProfile: 
![screen shot 2017-02-16 at 08 49 42](https://cloud.githubusercontent.com/assets/15426/23014222/56636148-f42e-11e6-8c60-1dda1cadebd8.png)

Seems there are PreparedStatements not closed properly: 
![screen shot 2017-02-16 at 09 58 09](https://cloud.githubusercontent.com/assets/15426/23014265/7ba3d0b4-f42e-11e6-9c4d-c508ede0c3ba.png)

**Comment by Aazhar** [comment]
This was resolved.
