### ISSUE TITLE
StringOutOfBoundException while processing dates

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#71]
I've got this problem several time, when harvesting from `2015-09-11`:
```
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                           doi not found
https://hal-enpc.archives-ouvertes.fr/hal-01194699/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01194699v1 extracted.
https://hal.archives-ouvertes.fr/hal-01194701/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01194701v1 extracted.
java.lang.StringIndexOutOfBoundsException: String index out of range: 7
        at java.lang.String.substring(String.java:1907)
        at fr.inria.anhalytics.commons.utilities.Utilities.completeDate(Utilities.java:171)
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.updatePublicationDate(HalTEIConverter.java:82)
        at fr.inria.anhalytics.harvest.teibuild.TeiBuilder.createTEICorpus(TeiBuilder.java:55)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.createTEICorpus(HALOAIPMHDomParser.java:291)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:241)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NullPointerException
        at fr.inria.anhalytics.commons.utilities.Utilities.generateIDs(Utilities.java:252)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:243)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        ... 6 more
log4j:WARN No such property [datePattern] in org.apache.log4j.ConsoleAppender.
```

However the date which we are considering is 
```
<imprint><publisher>Elsevier</publisher><biblScope unit="volume">795</biblScope><biblScope unit="pp">335–342</biblScope><date type="datePub">2015-06-16</date></imprint></monogr>
```

which looks correct. Any idea?

**Comment by lfoppiano** [comment]
OK so the value I get in input is `2007-`. What would be the expected output?
