### ISSUE TITLE
NullpointerException at Utilities.generateIDs

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#73]
I'm getting another `NullpointerException` when running the following comman:

```
 nohup java -Xmx2048m -jar target/anhalytics-harvest-0.1-SNAPSHOT.one-jar.jar -exe harvestAll -dFromDate 2016-06-27
```

here the stacktrace: 

```
java.lang.NullPointerException
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.transformMetadata(HalTEIConverter.java:226)
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.convertMetadataToTEIHeader(HalTEIConverter.java:52)
        at fr.inria.anhalytics.harvest.teibuild.TeiBuilder.createTEICorpus(TeiBuilder.java:49)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.createTEICorpus(HALOAIPMHDomParser.java:291)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:241)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NullPointerException
        at fr.inria.anhalytics.commons.utilities.Utilities.generateIDs(Utilities.java:253)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:243)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        ... 6 more
```

**Comment by lfoppiano** [comment]
I've got the same exception right now: 

```
[INFO ] fr.inria.anhalytics.commons.utilities.Utilities: http://api.archives-ouvertes.fr/oai/hal/?verb=ListRecords&metadataPrefix=xml-tei&from=2016-12-11&until=2016-12-11 **OK**
[INFO ] fr.inria.anhalytics.commons.utilities.Utilities: spend:8248 ms
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:           100 records found. processing...
https://hal.archives-ouvertes.fr/hal-01410521/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01410521v1 extracted.
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                           doi not found
https://hal.archives-ouvertes.fr/hal-01411247/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01411247v1 extracted.
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                           doi not found
https://hal.archives-ouvertes.fr/hal-01411968/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01411968v1 extracted.
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                           doi not found
https://hal.archives-ouvertes.fr/hal-01412009/document
[INFO ] fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser:                   tei of hal-01412009v1 extracted.
java.lang.NullPointerException
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.moveOrgToAffiliation(HalTEIConverter.java:263)
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.updateAffiliations(HalTEIConverter.java:290)
        at fr.inria.anhalytics.harvest.converters.HalTEIConverter.convertMetadataToTEIHeader(HalTEIConverter.java:58)
        at fr.inria.anhalytics.harvest.teibuild.TeiBuilder.createTEICorpus(TeiBuilder.java:49)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.createTEICorpus(HALOAIPMHDomParser.java:291)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:241)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NullPointerException
        at fr.inria.anhalytics.commons.utilities.Utilities.generateIDs(Utilities.java:253)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTei(HALOAIPMHDomParser.java:243)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHDomParser.getTeis(HALOAIPMHDomParser.java:80)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchDocumentsByDate(HALOAIPMHHarvester.java:46)
        at fr.inria.anhalytics.harvest.oaipmh.HALOAIPMHHarvester.fetchAllDocuments(HALOAIPMHHarvester.java:69)
        at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:85)
        at fr.inria.anhalytics.harvest.main.Main.main(Main.java:65)
        ... 6 more
```

@Aazhar the exception is stored in `/data/lfoppiano/anHALytics-core/anhalytics-harvest/nohup3`

It can be reproduced by processing the day `2016-12-11`

**Comment by Aazhar** [comment]
this is due to non existing organisation reference in the 'back' part !

`<tei:back>
<tei:listOrg type="structures" >
<tei:org type="laboratory" xml:id="struct-460687" status="INCOMING" >
<tei:orgName>Insitut Mathématique de Jussieu</tei:orgName>
<tei:orgName type="acronym" >IMJ-PRG</tei:orgName>
<tei:desc>
<tei:address>
<tei:addrLine>75205 PARIS CEDEX 13</tei:addrLine>
<tei:country key="FR" ></tei:country>
</tei:address>
</tei:desc>
<tei:listRelation>
<tei:relation active="#struct-0" type="direct" ></tei:relation>
</tei:listRelation>
</tei:org>
</tei:listOrg>
</tei:back> `

**Comment by Aazhar** [comment]
And for the first one it's because this notice having no title ! : https://hal.archives-ouvertes.fr/hal-01337963v1/tei

**Comment by lfoppiano** [comment]
The NPE has been resolved. I'm opening another task for dealing with documents without title
