### ISSUE TITLE
JavaHeap Space on TransformMetadata

### ISSUE THREAD

**Issue by lfoppiano** [anHALytics/anHALytics-core#99]
Running "Transform Metadata" with 2Gb of heap space, will result in 

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuilder.append(StringBuilder.java:190)
	at org.apache.commons.io.output.StringBuilderWriter.write(StringBuilderWriter.java:143)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2370)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2348)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2325)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2273)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1066)
	at fr.inria.anhalytics.commons.managers.MongoFileManager.getTei(MongoFileManager.java:395)
	at fr.inria.anhalytics.commons.managers.MongoFileManager.getMetadata(MongoFileManager.java:360)
	at fr.inria.anhalytics.harvest.teibuild.TeiCorpusBuilderProcess.transformMetadata(TeiCorpusBuilderProcess.java:52)
	at fr.inria.anhalytics.harvest.main.Main.processCommand(Main.java:118)
	at fr.inria.anhalytics.harvest.main.Main.main(Main.java:76)
18 Aug 2020 17:53.05 [INFO ] TeiBuilderWorker          - 	

```

I will attach more information below

The problem seems to occur for the documents: 
 - hal-00396570
 - hal-00396575

Update: even with 4Gb of Ram the OOM occurs anyway... it seems a problem with the XPATH

**Comment by lfoppiano** [comment]
OK First of all both DocumentBuilderFactory and DocumentBuilder are not thread safe..
